export type Future = { description: string, value: number }

export const lifeFutures: Future[] = [
    // Career
    { description: "You get promoted to team lead at work.", value: 10 },
    { description: "Your project fails, and you must start over.", value: -6 },
    { description: "You get invited to a prestigious industry conference.", value: 8 },
    { description: "You get laid off unexpectedly.", value: -10 },
    { description: "You receive a bonus for excellent performance.", value: 7 },
    { description: "A difficult coworker makes your job stressful.", value: -4 },
    { description: "You land a dream job at a top company.", value: 12 },
    { description: "Your work is criticised publicly.", value: -5 },
    { description: "You learn a valuable skill that boosts your career.", value: 9 },
    { description: "You are stuck in a boring role for months.", value: -3 },
    { description: "You successfully lead a high-profile project.", value: 11 },
    { description: "You miss a critical deadline and face consequences.", value: -7 },
    { description: "You mentor someone and gain recognition.", value: 8 },
    { description: "You are overworked and burnt out.", value: -8 },
    { description: "Your innovative idea is approved by management.", value: 10 },
    { description: "You are passed over for promotion.", value: -6 },
    { description: "You get a positive performance review.", value: 6 },
    { description: "You accidentally make a costly mistake.", value: -9 },
    { description: "You receive an unexpected promotion.", value: 12 },
    { description: "You feel unfulfilled despite success.", value: -4 },

    // Relationships
    { description: "You make a new close friend.", value: 7 },
    { description: "A friendship ends after a disagreement.", value: -5 },
    { description: "You start dating someone special.", value: 9 },
    { description: "You go through a painful breakup.", value: -8 },
    { description: "You reconcile with a past friend.", value: 6 },
    { description: "You face tension with a family member.", value: -4 },
    { description: "You meet someone who becomes a lifelong friend.", value: 10 },
    { description: "A misunderstanding creates conflict with a friend.", value: -3 },
    { description: "You celebrate a milestone with loved ones.", value: 8 },
    { description: "A relationship drifts apart slowly.", value: -6 },
    { description: "You help a friend in need and feel fulfilled.", value: 7 },
    { description: "Someone close betrays your trust.", value: -9 },
    { description: "You are invited to a joyful wedding.", value: 6 },
    { description: "A friend moves away and you feel lonely.", value: -5 },
    { description: "You form a new supportive social circle.", value: 9 },
    { description: "A family argument leaves lingering tension.", value: -4 },
    { description: "You reconnect with a childhood friend.", value: 7 },
    { description: "A friendship ends abruptly.", value: -7 },
    { description: "You help mediate a conflict successfully.", value: 6 },
    { description: "You experience unrequited love.", value: -6 },

    // Health & Lifestyle
    { description: "You start a fitness routine and feel energized.", value: 6 },
    { description: "You catch a minor illness that slows you down.", value: -3 },
    { description: "You complete a marathon or big physical challenge.", value: 8 },
    { description: "You suffer a small injury and need rest.", value: -4 },
    { description: "You improve your diet and feel healthier.", value: 5 },
    { description: "You experience fatigue from overworking.", value: -5 },
    { description: "You learn a meditation practice that reduces stress.", value: 7 },
    { description: "You develop a chronic health issue.", value: -10 },
    { description: "You achieve a personal best in a sport.", value: 9 },
    { description: "You catch a cold during an important event.", value: -2 },
    { description: "You consistently sleep well and feel refreshed.", value: 6 },
    { description: "You gain unwanted weight due to stress.", value: -4 },
    { description: "You start a new hobby that boosts your mental health.", value: 7 },
    { description: "You neglect exercise and feel lethargic.", value: -5 },
    { description: "You take a relaxing vacation.", value: 6 },
    { description: "You develop a minor injury while exercising.", value: -3 },
    { description: "You achieve a fitness goal.", value: 8 },
    { description: "You overexert yourself and need recovery.", value: -6 },
    { description: "You go hiking and enjoy nature.", value: 5 },
    { description: "You catch a seasonal illness.", value: -4 },

    // Finance
    { description: "You save a significant amount for future goals.", value: 7 },
    { description: "Unexpected expenses deplete your savings.", value: -6 },
    { description: "You make a successful investment.", value: 9 },
    { description: "You lose money in a failed investment.", value: -9 },
    { description: "You get a raise at work.", value: 8 },
    { description: "You incur a large debt unexpectedly.", value: -10 },
    { description: "You find a lucrative side hustle.", value: 6 },
    { description: "You mismanage your budget and overspend.", value: -5 },
    { description: "You receive a financial windfall.", value: 10 },
    { description: "Your car breaks down, causing expense.", value: -4 },
    { description: "You pay off a major debt.", value: 7 },
    { description: "A scam costs you money.", value: -8 },
    { description: "You invest in cryptocurrency successfully.", value: 9 },
    { description: "You miss a bill and get fines.", value: -3 },
    { description: "You sell an item at a good profit.", value: 5 },
    { description: "Unexpected medical bills arrive.", value: -7 },
    { description: "You negotiate a raise successfully.", value: 8 },
    { description: "You make a poor investment decision.", value: -6 },
    { description: "You receive a bonus from a client.", value: 6 },

    // Personal growth / experiences
    { description: "You travel to a country you’ve always wanted to visit.", value: 8 },
    { description: "You learn a new skill that opens opportunities.", value: 7 },
    { description: "You experience a stressful challenge that shakes your confidence.", value: -5 },
    { description: "You reconnect with someone from your past, bringing joy.", value: 6 },
    { description: "You attend a workshop that inspires creativity.", value: 7 },
    { description: "You face rejection from a project or opportunity.", value: -6 },
    { description: "You write a personal journal and gain insight.", value: 5 },
    { description: "You fail at a new hobby.", value: -4 },
    { description: "You successfully complete an online course.", value: 6 },
    { description: "You forget an important personal commitment.", value: -3 },
    { description: "You meet a mentor who guides your growth.", value: 9 },
    { description: "You procrastinate and miss an opportunity.", value: -5 },
    { description: "You volunteer for a meaningful cause.", value: 7 },
    { description: "You get lost during travel and feel anxious.", value: -2 },
    { description: "You attend a cultural festival and enjoy new experiences.", value: 6 },
    { description: "You attempt a new skill and succeed.", value: 8 },
    { description: "You overcommit and feel stressed.", value: -4 },
    { description: "You read a life-changing book.", value: 5 },
    { description: "You neglect personal growth activities.", value: -3 },

    // Luck / Random Events
    { description: "You find money on the street.", value: 3 },
    { description: "You spill coffee on an important document.", value: -3 },
    { description: "You win a small lottery prize.", value: 5 },
    { description: "You get a parking ticket.", value: -2 },
    { description: "You have an unexpected encounter that cheers you up.", value: 4 },
    { description: "A sudden storm ruins your outdoor plans.", value: -3 },
    { description: "You find a rare collectible item.", value: 6 },
    { description: "You get stuck in traffic and are late.", value: -2 },
    { description: "You discover a hidden talent by accident.", value: 7 },
    { description: "A pet causes minor chaos at home.", value: -1 },
    { description: "You receive a thoughtful gift from a stranger.", value: 5 },
    { description: "You lose your wallet temporarily.", value: -4 },
    { description: "You win a trivia contest.", value: 6 },
    { description: "A minor accident happens but no one is hurt.", value: -2 },
    { description: "You meet someone influential unexpectedly.", value: 8 },
    { description: "You accidentally damage something valuable.", value: -5 },
    { description: "You get a free meal at a restaurant.", value: 3 },
    { description: "Your flight is delayed for hours.", value: -3 },
    { description: "You get a chance to try a new activity for free.", value: 4 },
];